import { createRequire } from 'node:module';
import { once } from 'node:events';
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
import { openStore } from '../src/store.js';
import { createApp } from '../src/server.js';
import { acceptUpdate,flushOutbox } from '../src/bot.js';
const require=createRequire(import.meta.url);
let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright'));}
const store=openStore();const server=createApp({store,testRoles:true,botStatus:{state:'connected',username:'test_bot'}});server.listen(0,'127.0.0.1');await once(server,'listening');let browser;
try{
 browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(8000);
 await page.goto(`http://127.0.0.1:${server.address().port}`);await page.locator('#login').waitFor({state:'visible'});
 await page.getByRole('button',{name:'Регистрация',exact:true}).click();await page.locator('#username').fill('tester');await page.locator('#password').fill('test-password-2026');await page.locator('#password-repeat').fill('test-password-2026');await page.getByRole('button',{name:'Создать аккаунт',exact:true}).click();await page.locator('#workspace').waitFor({state:'visible'});
 const createLead=async()=>{await page.locator('#add').click();await page.getByLabel('Имя',{exact:true}).fill('Анна Смирнова');await page.getByLabel('Контакт',{exact:true}).fill('@anna_demo');await page.getByLabel('Запрос',{exact:true}).fill('Нужен лендинг для запуска продукта');await page.getByLabel('Компания',{exact:true}).fill('Студия Север');await page.getByLabel('Сумма сделки, ₽').fill('150000');await page.getByLabel('Теги',{exact:true}).fill('Лендинг, Приоритет');await page.getByRole('button',{name:'Сохранить лида',exact:true}).click();};
 await createLead();await page.locator('#rows').getByText('Анна Смирнова',{exact:true}).waitFor();
 await createLead();await page.locator('#duplicate-dialog').waitFor({state:'visible'});await page.getByRole('button',{name:'Нет, вернуться'}).click();assert.equal(store.list().length,1);await page.getByRole('button',{name:'Сохранить лида',exact:true}).click();await page.getByRole('button',{name:'Да, создать дубль'}).click();await page.locator('#editor').waitFor({state:'hidden'});assert.equal(store.list().length,2);
 await page.locator('[data-view="pipeline"]').click();const first=page.locator('[data-stage]').first();await first.selectOption('proposal');await page.waitForFunction(()=>document.querySelector('.pipeline-column:nth-child(3) .pipeline-card'));
 mkdirSync('artifacts',{recursive:true});await page.screenshot({path:'artifacts/v2-pipeline.png',fullPage:true});
 await page.locator('[data-view="tasks"]').click();await page.locator('#add-task').click();await page.getByLabel('Название задачи',{exact:true}).fill('Позвонить клиенту');await page.getByLabel('Описание',{exact:true}).fill('Обсудить бюджет и сроки');
 const local=v=>{const d=new Date(v);return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
 await page.locator('#task-due').fill(local(Date.now()+3600000));await page.locator('#task-remind').fill(local(Date.now()-60000));await page.getByRole('button',{name:'Сохранить задачу',exact:true}).click();await page.locator('#task-list').getByRole('button',{name:'Позвонить клиенту',exact:true}).waitFor();assert.equal(store.tasks().length,1);
 await page.locator('#notifications-button').click();await page.locator('#notification-list').getByText('Задача: Позвонить клиенту',{exact:true}).waitFor();await page.getByRole('button',{name:'Прочитано',exact:true}).click();await page.getByRole('button',{name:'Закрыть напоминания'}).click();await page.screenshot({path:'artifacts/v2-tasks.png',fullPage:true});
 await page.locator('[data-view="messages"]').click();await page.locator('#message-body').fill('Команда, новая заявка в работе');await page.getByRole('button',{name:'Отправить',exact:true}).click();await page.locator('#chat-messages').getByText('Команда, новая заявка в работе',{exact:true}).waitFor();
 let id=0;for(const text of ['/start','Борис','@boris','Реклама'])acceptUpdate(store,{update_id:++id,message:{chat:{id:17,type:'private'},from:{id:17},text}});
 await page.locator('#refresh').click();await page.locator('#telegram-chat-tab').click();await page.locator('#chat-messages').getByText('Реклама',{exact:true}).waitFor();await page.locator('#message-body').fill('Борис, здравствуйте! Обсудим задачу.');await page.getByRole('button',{name:'Отправить',exact:true}).click();await page.locator('#chat-messages').getByText('Борис, здравствуйте! Обсудим задачу.',{exact:true}).waitFor();assert.ok(store.db.prepare('SELECT text FROM outbox').all().some(r=>r.text.includes('Борис, здравствуйте')));await flushOutbox(store,async()=>{});await page.locator('#refresh').click();await page.screenshot({path:'artifacts/v2-messenger.png',fullPage:true});
 await page.locator('[data-view="team"]').click();await page.locator('#self-role').selectOption('observer');await page.waitForFunction(()=>document.querySelector('#current-role').textContent==='Наблюдатель');await page.locator('[data-view="leads"]').click();assert.equal(await page.locator('#add').isVisible(),false);await page.locator('[data-edit]').first().click();assert.equal(await page.locator('#save').isVisible(),false);await page.getByRole('button',{name:'Закрыть карточку'}).click();await page.locator('[data-view="team"]').click();await page.locator('#self-role').selectOption('admin');await page.waitForFunction(()=>document.querySelector('#current-role').textContent==='Администратор');
 await page.setViewportSize({width:390,height:844});for(const section of ['leads','pipeline','tasks','messages','team']){await page.locator(`[data-view="${section}"]`).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`No mobile overflow: ${section}`);await page.screenshot({path:`artifacts/v2-mobile-${section}.png`,fullPage:true});}
 await page.locator('[data-view="tasks"]').click();await page.locator('#add-task').click();await page.screenshot({path:'artifacts/v2-mobile-task-form.png',fullPage:true});await page.keyboard.press('Escape');
 await page.locator('#logout').click();await page.locator('#login').waitFor({state:'visible'});await page.locator('#login-mode').click();await page.locator('#password').fill('test-password-2026');await page.locator('#auth-submit').click();await page.locator('#workspace').waitFor({state:'visible'});
 assert.deepEqual(errors,[]);console.log('Browser checks passed: registration, duplicate cancellation/confirmation, pipeline, task reminder, team chat, Telegram reply queue, role switch, mobile layout, logout/login.');
}finally{if(browser)await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));store.close();}

